# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Pull Request Triggers (triggers the pipeline whenever a pull request is opened with the specified target branches)
trigger: none

pr:
  branches:
    include:
    - main
  paths:
    exclude: # file paths which will not trigger a build
    - README.md
    - .gitignore

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- script: |
    sudo apt-get update
    sudo apt-get install zip -y
    sudo apt-get install build-essential -y
    sudo apt-get install cmake -y
    sudo apt-get update
    sudo apt-get install cppcheck -y
    ls
    gcc --version
  displayName: 'Install sofwares'

- script: |
    echo STARTING sec scanning
    mkdir build
    cppcheck -x --check-config -I ./.pipelines --cppcheck-build-dir=build --enable=all . > scanning_log.txt
    grep "warning" scanning_log.txt
    echo Done Grepping
    chmod u+x process_sec_scanning_output.sh ./process_sec_scanning_output.sh
  displayName: 'Run Security Scanning'

- script: |
   sudo apt-get install -y clang
   clang --version
   clang -g -O1 -fsanitize=address,fuzzer ./FuzzerMain.cpp -o ./FuzzerMain.out
   ls
   ./FuzzerMain.out -timeout=10
  displayName: 'Install Fuzzing Tool'