# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Pull Request Triggers (triggers the pipeline whenever a pull request is opened with the specified target branches)
trigger: none

pr:
  branches:
    include:
    - main
  paths:
    exclude: # file paths which will not trigger a build
    - README.md
    - .gitignore

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- script: |
    echo install Flawfinder
    pip install flawfinder
    sudo apt-get -y install libfuzzer-11-dev
  displayName: 'install Flawfinder and libfuzzer'


- script: |
    echo Run Flawfinder
    flawfinder .pipelines
  displayName: 'Run Flawfinder'

- script: |
    echo Run libfuzzer
    ./.pipelines/fuzz_target -max_total_time=60 -artifact_prefix=./.pipelines/crash_dir/ -max_len=2048 ./.pipelines/corpus_dir1.
  displayName: 'Run libfuzzer'